description: VIP玩家+举报管理
name: VipReport
main: com.example.vipreport.VipReportPlugin
version: 2.12-Fix
api-version: 1.16
commands:
  report:
    description: 举报命令
    usage: /report <玩家> <原因>
  vip:
    description: 管理员管理VIP命令
    usage: /vip <add/remove> <玩家>
permissions:
  vipreport.use:
    description: 使用举报功能
    default: false
  vipreport.admin:
    description: 管理VIP权限
    default: op
